START_BUTTON_TEXT = "Заполнить анкету 🚀"
START_BUTTON_CALL = "start"

MALE_BUTTON = "Муж."
FEMALE_BUTTON = "Жен."
MALE_CALL = "male"
FEMALE_CALL = "female"

START_DATING_CALL = "start_dating"
START_DATING_BUTTON = "1️⃣ Начать знакомство"
SET_PREFERENCES_CALL = "set_preferences"
SET_PREFERENCES_BUTTON = "2️⃣ Выставить предпочтения по поиску"
EDIT_PROFILE_CALL = "edit_profile"
EDIT_PROFILE_BUTTON = "3️⃣ Редактировать свой профиль"
VIEW_RATING_CALL = "view_rating"
VIEW_RATING_BUTTON = "4️⃣ Посмотреть свой рейтинг"
VIEW_MATCHES_CALL = "view_matches"
VIEW_MATCHES_BUTTON = "5️⃣ Взаимные совпадения"

MIN_AGE_CALL = "min_age"
MIN_AGE_BUTTON = "Минимальный возраст"
MAX_AGE_CALL = "max_age"
MAX_AGE_BUTTON = "Максимальный возраст"
MIN_RATING_CALL = "min_rating"
MIN_RATING_BUTTON = "Минимальный рейтинг"
MAX_RATING_CALL = "max_rating"
MAX_RATING_BUTTON = "Максимальный рейтинг"
RETURN_ACTION_CALL = "return_action"
RETURN_ACTION_BUTTON = "Вернутся к выбору действий"

EDIT_PHOTO_CALL = "edit_photo"
EDIT_PHOTO_BUTTON = "1️⃣ Редактировать фото"
EDIT_NAME_CALL = "edit_name"
EDIT_NAME_BUTTON = "2️⃣ Редактировать ФИО"
EDIT_GENDER_CALL = "edit_gender"
EDIT_GENDER_BUTTON = "3️⃣ Редактировать пол"
EDIT_AGE_CALL = "edit_age"
EDIT_AGE_BUTTON = "4️⃣ Редактировать возраст"
EDIT_BIO_CALL = "edit_bio"
EDIT_BIO_BUTTON = "5️⃣ Редактировать рассказ о себе"
EDIT_ALL_CALL = "edit_all"
EDIT_ALL_BUTTON = "6️⃣ Изменить профиль целиком"
EDIT_BACK_CALL = "edit_back"
EDIT_BACK_BUTTON = "7️⃣ Вернуться к выбору действий"

LIKE_CALL = "like_profile"
LIKE_BUTTON = "❤️ Лайк"
DISLIKE_CALL = "dislike_profile"
DISLIKE_BUTTON = "👎 Дизлайк"
BACK_TO_MENU_CALL = "back_to_menu"
BACK_TO_MENU_BUTTON = "↩️ Вернуться к выбору действий"
