START_BUTTON_TEXT = "Заполнить анкету 🚀"
START_BUTTON_CALL = "start"

MALE_BUTTON = "Муж."
FEMALE_BUTTON = "Жен."
MALE_CALL = "male"
FEMALE_CALL = "female"

START_DATING_CALL = "start_dating"
START_DATING_BUTTON = "1️⃣ Начать знакомство"
SET_PREFERENCES_CALL = "set_preferences"
SET_PREFERENCES_BUTTON = "2️⃣ Выставить предпочтения по поиску"
EDIT_PROFILE_CALL = "edit_profile"
EDIT_PROFILE_BUTTON = "3️⃣ Редактировать свой профиль"
VIEW_LIKES_CALL = "view_likes"
VIEW_LIKES_BUTTON = "4️⃣ Посмотреть свои лайки"
VIEW_RATING_CALL = "view_rating"
VIEW_RATING_BUTTON = "5️⃣ Посмотреть свой рейтинг"
VIEW_COMMENTS_RECEIVED_CALL = "view_comments_received"
VIEW_COMMENTS_RECEIVED_BUTTON = "6️⃣ Комментарии, которые написали мне"
VIEW_COMMENTS_SENT_CALL = "view_comments_sent"
VIEW_COMMENTS_SENT_BUTTON = "7️⃣ Комментарии, которые написал я"
VIEW_MATCHES_CALL = "view_matches"
VIEW_MATCHES_BUTTON = "8️⃣ Взаимные совпадения"
